### ISSUE TITLE
NumPy array is not writeable, and PyTorch does not support non-writeable tensors

### ISSUE THREAD

**Issue by frmunoz** [TheoreticalEcology/s-jSDM#24]
Dear colleagues,

I have the following issue when attempting to run s-jSDM with the R package:

..\torch\csrc\utils\tensor_numpy.cpp:141: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program.

I don't figure out what is the problem here, and how to resolve it.
Do you have any idea?

Best wishes,

François

**Comment by MaximilianPi** [comment]
Hi François,
this seems like a pytorch specific problem. Can you please provide more information about your setup (cpu or gpu, torch version ($conda info))? If you have installed sjSDM via conda (or install_sjSDM()), you can use the new function install_diagnostic(), which I pushed today (which means you have to fetch the latest version and re-install sjSDM). 

Best wishes,
Max

**Comment by frmunoz** [comment]
Hello Max,

Thank you for your answer!

I have defined a cpu setup.
Here is the output of install_diagnostic() on my machine:

active environment : None
       user config file : C:\Users\admmunoz\Documents\.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
       base environment : C:\PROGRA~3\ANACON~1  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\PROGRA~3\ANACON~1\pkgs
                          C:\Users\admmunoz\Documents\.conda\pkgs
                          C:\Users\admmunoz\AppData\Local\conda\conda\pkgs
       envs directories : C:\PROGRA~3\ANACON~1\envs
                          C:\Users\admmunoz\Documents\.conda\envs
                          C:\Users\admmunoz\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False


Best wishes,

François

**Comment by MaximilianPi** [comment]
Hi François,
unfortunately, at the moment the automatic pytorch installation is still unstable but I am actively working on this. 
I committed today a few installation updates, that's why I suggest the following procedure:
1) Remove the "old" conda environment, run in R:
`reticulate::conda_remove("s-sjSDM")`
2) Download and install the newest version of s-jSDM:
`devtools::install_github("https://github.com/TheoreticalEcology/s-jSDM", subdir = "sjSDM")
`
3) Install pytorch via 
`library(sjSDM)`
`install_sjSDM()`
4) If this still did not work, post here the output of:
`install_diagnostic()`

Cheers,
Max

**Comment by florianhartig** [comment]
I'm surprised that this ran at all, because I thought conda 4.8.3 can't install pytorch - did the install really work, or did it not, in which case the error message should be improved.

**Comment by MaximilianPi** [comment]
This is a significant issue. I will report this to the pytorch community and we have to update our installation instructions... install_sjSDM() installs now automatically conda 4.8.2 so it affects only people who install anaconda themselves

**Comment by MaximilianPi** [comment]
Okay, I found the source of this warning. There seems to be no issue with conda 4.8.3 on Linux/Windows but with PyTorch 1.5 and reticulate:
- reticulate translates R matrices to non writeable numpy arrays:
 (`reticulate::r_to_py(matrix(0.0))$flags`)
- With 1.5 the pytorch team implemented a warning when a non-writeable numpy array is transformed to a tensor (in our case that happens when the env and occ matrices (X, Y) are transformed to torch tensors.
- It does not influence the model's behavior, performance, or results (see [PyTorch commit: Warns on read-only Numpy array->tensor conversion (#33615)](https://github.com/pytorch/pytorch/commit/7e55494502478d7f78138bc974e681df52b0635c))
- For now, I create copies of the actual data, which is not optimal but at least the data is still on the cpu (under the assumption that the cpu memory is not the bottleneck)
 
https://github.com/TheoreticalEcology/s-jSDM/blob/cc66b35a79f747a4bf1da4d2a6fa6a3d710bcb55/sjSDM/inst/python/sjSDM_py/model_new.py#L119-L125

**Comment by frmunoz** [comment]
Thank you very much for your answers and update of the package.
I can run now the model, but my dataset is too large for the memory I have on my PC... I will try to find a different way.

FYI, here is the new diagnostic I get with the lastest version,
### active environment : None
       user config file : C:\Users\admmunoz\Documents\.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
       base environment : C:\PROGRA~3\ANACON~1  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\PROGRA~3\ANACON~1\pkgs
                          C:\Users\admmunoz\Documents\.conda\pkgs
                          C:\Users\admmunoz\AppData\Local\conda\conda\pkgs
       envs directories : C:\PROGRA~3\ANACON~1\envs
                          C:\Users\admmunoz\Documents\.conda\envs
                          C:\Users\admmunoz\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

**Comment by MaximilianPi** [comment]
There are two ways to reduce the memory strain:
1. step_size (in sjSDM(...step_size=): By default it is set to 10% of your number sites, which is high if you have hundreds/thousands of sites or species. Maybe setting it to 1 - 20 could resolve this.
2. Setting manually the "df" option in biotic=bioticStruct(df = XX). df controls the rank of the sigma matrix. By default it is set to (number of species/2) and by reducing it you lose degree of freedoms for the covariance matrix but you also reduce the memory strain

**Comment by MaximilianPi** [comment]
I will keep this open... something in the code still causes the warning to appear (it appears after the tests... but I'm unable to track it down, 384 tests and the msg only appears once a session).

For now, the work-around is to use `reticulate::r_to_py(matrix)$copy() i`nstead of the R-matrix when calling a python function.
