### ISSUE TITLE
error: ModuleNotFoundError: No module named 'pyro'

### ISSUE THREAD

**Issue by frmunoz** [TheoreticalEcology/s-jSDM#33]
Dear Max,

I have the following error when installing the latest version of the package:

`.onLoad failed in loadNamespace() for 'sjSDM', details:
 call: py_module_import(module, convert = convert)
error: ModuleNotFoundError: No module named 'pyro'`

However, pyro has been installed on my Windows system with Anaconda.
Maybe there is a path to change somewhere to allow proper installation.

Best wishes,

François

**Comment by MaximilianPi** [comment]
Hi François,

> However, pyro has been installed on my Windows system with Anaconda.

From this I assume that you installed pyro manually? Maybe pyro was not installed into the right environment. Pyro can only be installed by pip, however, calling pip (even from the right environment) might not call the correct pip from the environment:

This might not work:
```
$ conda activate r-reticulate
$ (r-reticulate) pip install pyro-ppl
```
better:
```
$ conda activate r-reticulate
$ (r-reticulate) python -m pip install pyro-ppl
```
Theoretically, calling install_sjSDM() again should also fix this (I added the pyro dependency ~5 days ago). I suggest you first try it with install_sjSDM(). 

If it does not work with install_sjSDM(), I have to think about splitting the python pkg and the dependencies, because pyro is only needed for the new sLVM() function, which can be seperated from the rest of the python package.

François, thanks for hanging in there. Pyro will be the last dependency and if I get it installed properly, we can go for the first release.

Best wishes,
Max

**Comment by frmunoz** [comment]
Dear Max,

You are right, I previously reinstalled pyro in another way. I have followed your tips, and now sjSDM can be installed.

However, I did reinstall pyro when trying to solve another issue, and this former issue is now back:

```> torch
<pointer: 0x0>
```
Because of that, it is not possible to run sjSDM presently on my machine.

Best wishes,

François

**Comment by frmunoz** [comment]
I add the current outcome of `install_diagnostic` in case it can help.

```
          name                                                     python
1    Anaconda3                     C:\\ProgramData\\Anaconda3\\python.exe
2 r-reticulate C:\\ProgramData\\Anaconda3\\envs\\r-reticulate\\python.exe
3      r-sjSDM      C:\\ProgramData\\Anaconda3\\envs\\r-sjSDM\\python.exe



ENV: Anaconda3


torch:

EnvironmentLocationNotFound: Not a conda environment: C:\PROGRA~3\ANACON~1\envs\Anaconda3



numpy:

EnvironmentLocationNotFound: Not a conda environment: C:\PROGRA~3\ANACON~1\envs\Anaconda3



ENV: r-reticulate


torch:
# packages in environment at C:\PROGRA~3\ANACON~1\envs\r-reticulate:
#
# Name                    Version                   Build  Channel
pytorch                   1.5.0               py3.6_cpu_0  [cpuonly]  pytorch
torchvision               0.6.0                  py36_cpu  [cpuonly]  pytorch


numpy:
# packages in environment at C:\PROGRA~3\ANACON~1\envs\r-reticulate:
#
# Name                    Version                   Build  Channel
numpy                     1.18.2                   pypi_0    pypi
numpy-base                1.18.1           py36hc3f5095_1  


ENV: r-sjSDM


torch:
# packages in environment at C:\PROGRA~3\ANACON~1\envs\r-sjSDM:
#
# Name                    Version                   Build  Channel
pytorch                   1.5.0               py3.6_cpu_0  [cpuonly]  pytorch
torchvision               0.6.0                  py36_cpu  [cpuonly]  pytorch


numpy:
# packages in environment at C:\PROGRA~3\ANACON~1\envs\r-sjSDM:
#
# Name                    Version                   Build  Channel
numpy                     1.18.1           py36h48dd78f_1    conda-forge


python:         C:/ProgramData/Anaconda3/envs/r-reticulate/python.exe
libpython:      C:/ProgramData/Anaconda3/envs/r-reticulate/python36.dll
pythonhome:     C:/ProgramData/Anaconda3/envs/r-reticulate
version:        3.6.10 |Anaconda, Inc.| (default, Mar 23 2020, 17:58:33) [MSC v.1916 64 bit (AMD64)]
Architecture:   64bit
numpy:          C:/ProgramData/Anaconda3/envs/r-reticulate/Lib/site-packages/numpy
numpy_version:  1.18.1
torch:          C:\PROGRA~3\ANACON~1\envs\R-RETI~1\lib\site-packages\torch\__init__.p

python versions found: 
 C:/ProgramData/Anaconda3/envs/r-reticulate/python.exe
 C:/Users/admmunoz/AppData/Local/Programs/Python/Python37-32/python.exe
 C:/ProgramData/Anaconda3/python.exe
 C:/ProgramData/Anaconda3/envs/r-sjSDM/python.exe




     active environment : None
       user config file : C:\Users\admmunoz\Documents\.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.1
       base environment : C:\PROGRA~3\ANACON~1  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\PROGRA~3\ANACON~1\pkgs
                          C:\Users\admmunoz\Documents\.conda\pkgs
                          C:\Users\admmunoz\AppData\Local\conda\conda\pkgs
       envs directories : C:\PROGRA~3\ANACON~1\envs
                          C:\Users\admmunoz\Documents\.conda\envs
                          C:\Users\admmunoz\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by frmunoz** [comment]
I feel there is an issue with use of `pytorch ` with gpu version, but I am confused because it did work with gpu version a few days ago.

**Comment by MaximilianPi** [comment]
Hi François,

> <pointer: 0x0>
Because of that, it is not possible to run sjSDM presently on my machine.

This is normal when you restart the R session without cleaning the environment. Restarting a clean and new session should solve this. But it's weird, sjSDM() should still work because I added in the function a checker for the null pointer and which enforces a reload of the python modules, so even if torch == <pointer: 0x0> the sjSDM() should still work. 

The diagnostic shows that you have two conda environments with pytorch: r-sjSDM and r-reticulate. s-jSDM is the old environment (name) we used until a week ago (so it is our fault that there two environments). You should remove this environment, because otherwise, sjSDM will switch between the two environments but the old one has no pyro and you get another error. 
You can delete the "s-jSDM" environment from within R with:
`reticulate::conda_remove("r-sjSDM")`

> I feel there is an issue with use of pytorch with gpu version, but I am confused because it did work with gpu version a few days ago.

Do you have a NVIDIA GPU? Because at the moment you have the CPU pytorch versions installed and you cannot run the models on the GPU even if you have one. 

Best wishes,
Max

**Comment by frmunoz** [comment]
Dear Max,

I finally could solve the "cpuonly" issue with pytorch (it was in r-reticulate envt, not in base...).

Now the issue should no longer happen. :-)

Best,

François
