### ISSUE TITLE
test can't run in 0.1.8

### ISSUE THREAD

**Issue by CaiWang0503** [TheoreticalEcology/s-jSDM#69]
hi there,
when i update to 0.1.8 and run the test model, it throws an error.
 what happen with my mac?
<img width="737" alt="Screen Shot 2021-06-17 at 7 07 11 PM" src="https://user-images.githubusercontent.com/48045062/122386056-0cb77a00-cfa0-11eb-9097-c915715ef228.png">

**Comment by MaximilianPi** [comment]
Hi Cai Wang,
the package is not yet compatible with torch 1.9 (which was published this week), I will fix this asap.

**Comment by MaximilianPi** [comment]
I pushed a fix. The problem was that the tensordot function didn't has the same signature for torch and torchscript in the past (an additional jit compilation step we use), see https://pytorch.org/docs/stable/jit_unsupported.html. PyTorch 1.9 seems to fix this behaviour but it would break compatibility with older versions. But I was able to solve this issue by using einsum instead of tensordot.
